In [1]:
import pandas as pd
import numpy as np

In [2]:
df_superjob = pd.read_csv('superjob.csv')

In [3]:
df_superjob.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19822 entries, 0 to 19821
Data columns (total 58 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0                     19822 non-null  int64
 1   canEdit                        19822 non-null  bool
 2   is_closed                      19822 non-null  bool
 3   id                             19822 non-null  int64
 4   id_client                      19822 non-null  int64
 5   payment_from                   19822 non-null  int64
 6   payment_to                     19822 non-null  int64
 7   date_pub_to                    19822 non-null  int64
 8   date_archived                  19822 non-null  int64
 9   date_published                 19822 non-null  int64
 10  address                        13329 non-null  object
 11  profession                     19822 non-null  object
 12  work                           0 non-null      float64
 13  compensation                   0 non-null      float64
 14  candidat                       19822 non-null  object
 15  metro                          19822 non-null  object
 16  currency                       19822 non-null  object
 17  vacancyRichText                19822 non-null  object
 18  covid_vaccination_requirement  19822 non-null  object
 19  trud_vsem                      19822 non-null  object
 20  moveable                       19822 non-null  bool
 21  agreement                      19822 non-null  bool
 22  anonymous                      19822 non-null  bool
 23  is_archive                     19822 non-null  bool
 24  is_storage                     19822 non-null  bool
 25  type_of_work                   19822 non-null  object
 26  place_of_work                  19822 non-null  object
 27  education                      19822 non-null  object
 28  experience                     19822 non-null  object
 29  maritalstatus                  19822 non-null  object
 30  children                       19822 non-null  object
 31  client                         19822 non-null  object
 32  languages                      19822 non-null  object
 33  driving_licence                19822 non-null  object
 34  catalogues                     19822 non-null  object
 35  agency                         19822 non-null  object
 36  town                           19822 non-null  object
 37  already_sent_on_vacancy        19822 non-null  bool
 38  rejected                       19822 non-null  bool
 39  response_info                  19822 non-null  object
 40  phone                          7122 non-null   object
 41  phones                         7122 non-null   object
 42  fax                            0 non-null      float64
 43  faxes                          0 non-null      float64
 44  client_logo                    10364 non-null  object
 45  highlight                      19822 non-null  bool
 46  age_from                       19822 non-null  int64
 47  age_to                         19822 non-null  int64
 48  gender                         19822 non-null  object
 49  firm_name                      19822 non-null  object
 50  firm_activity                  19742 non-null  object
 51  link                           19822 non-null  object
 52  latitude                       12746 non-null  float64
 53  longitude                      12746 non-null  float64
 54  vacancy_category               19822 non-null  object
 55  experience_level               19822 non-null  int64
 56  contacts_hidden                5737 non-null   object
 57  contact_hiding_cause           5737 non-null   object
dtypes: bool(10), float64(6), int64(11), object(31)
memory usage: 7.4+ MB

In [4]:
df_superjob['firm_name']

0                       Аэрофлот
1            OZON: Старт карьеры
2                           КРОК
3                         Добрый
4                         Disney
                  ...
19817                     билайн
19818                        ФТС
19819              ООО "ПРОФ-НН"
19820    Группа Компаний РУСАГРО
19821                        TNK
Name: firm_name, Length: 19822, dtype: object

In [5]:
cols_to_keep = ['vacancy_category', 'profession', 'payment_from', 'payment_to', 'currency',
                'candidat', 'vacancyRichText', 'town', 'experience',
                'type_of_work', 'place_of_work', 'firm_name']

In [6]:
df = df_superjob[cols_to_keep]

In [7]:
df

,vacancy_category,profession,payment_from,payment_to,currency,candidat,vacancyRichText,town,experience,type_of_work,place_of_work,firm_name
0,AI,Стажер в IT отдел,0,0,rub,"Образование: программирование, интеллектуальны...","Образование: программирование, интеллектуальн...","{'id': 4, 'title': 'Москва', 'declension': 'в ...","{'id': 1, 'title': 'Без опыта'}","{'id': 6, 'title': 'Полный рабочий день'}","{'id': 0, 'title': 'Не имеет значения'}",Аэрофлот
1,AI,Стажер разработчик интерфейсов,0,0,rub,Команда Банка Ozon создаёт и развивает сервисы...,<p>Команда Банка Ozon создаёт и развивает серв...,"{'id': 4, 'title': 'Москва', 'declension': 'в ...","{'id': 1, 'title': 'Без опыта'}","{'id': 6, 'title': 'Полный рабочий день'}","{'id': 0, 'title': 'Не имеет значения'}",OZON: Старт карьеры
2,AI,Контент-маркетолог,0,0,rub,"Привет,\nВ команде #mktngCROC открылась ваканс...","<p>Привет,</p>В команде #mktngCROC открылась в...","{'id': 4, 'title': 'Москва', 'declension': 'в ...","{'id': 1, 'title': 'Без опыта'}","{'id': 6, 'title': 'Полный рабочий день'}","{'id': 0, 'title': 'Не имеет значения'}",КРОК
3,AI,Стажер в IT отдел,0,0,rub,Здесь занимаются поддержкой IT-платформ и их р...,Здесь занимаются поддержкой IT-платформ и их ...,"{'id': 4, 'title': 'Москва', 'declension': 'в ...","{'id': 1, 'title': 'Без опыта'}","{'id': 6, 'title': 'Полный рабочий день'}","{'id': 0, 'title': 'Не имеет значения'}",Добрый
4,AI,Стажер отдела операционной деятельности цифров...,0,0,rub,О компании и роли\n\nГруппа по управлению опер...,<p><b> О компании и роли</b><br><br>Группа по ...,"{'id': 4, 'title': 'Москва', 'declension': 'в ...","{'id': 1, 'title': 'Без опыта'}","{'id': 6, 'title': 'Полный рабочий день'}","{'id': 0, 'title': 'Не имеет значения'}",Disney
...,...,...,...,...,...,...,...,...,...,...,...,...
19817,"Начало карьеры, мало опыта",Специалист по расклейке листовок (подработка),20000,60000,rub,"Мы предлагаем:\n• Гибкий график, от 4 часов в ...",<p><b>Мы предлагаем:</b></p><ul><li>Гибкий гра...,"{'id': 12, 'title': 'Нижний Новгород', 'declen...","{'id': 1, 'title': 'Без опыта'}","{'id': 13, 'title': 'Частичная занятость / Сов...","{'id': 0, 'title': 'Не имеет значения'}",билайн
19818,"Начало карьеры, мало опыта","Системный администратор, IT-специалист (госслу...",65000,70000,rub,Обязанности:\n• Информационная безопасность (П...,<p><b><br /></b></p><b>Обязанности:</b><ul><li...,"{'id': 12, 'title': 'Нижний Новгород', 'declen...","{'id': 2, 'title': 'От 1 года'}","{'id': 6, 'title': 'Полный рабочий день'}","{'id': 0, 'title': 'Не имеет значения'}",ФТС
19819,"Начало карьеры, мало опыта",Инженер-оператор КИМ и ВИМ,0,90000,rub,"Вакансия компании: ООО ""ПРОФ-НН""\nОписание ком...","<p>Вакансия компании: ООО ""ПРОФ-НН""</p><p>Опис...","{'id': 12, 'title': 'Нижний Новгород', 'declen...","{'id': 2, 'title': 'От 1 года'}","{'id': 6, 'title': 'Полный рабочий день'}","{'id': 0, 'title': 'Не имеет значения'}","ООО ""ПРОФ-НН"""
19820,"Начало карьеры, мало опыта",DevOps специалист,0,0,rub,В ГК Русагро открыта вакансия DevOps\nЧто нужн...,<p>В ГК Русагро открыта вакансия DevOps</p><p>...,"{'id': 12, 'title': 'Нижний Новгород', 'declen...","{'id': 3, 'title': 'От 3 лет'}","{'id': 6, 'title': 'Полный рабочий день'}","{'id': 0, 'title': 'Не имеет значения'}",Группа Компаний РУСАГРО
19821,"Начало карьеры, мало опыта",Инженер ПНР АСУТП,103000,118000,rub,Обязанности:\n• Ввод в эксплуатацию шкафного о...,<b>Обязанности:</b><ul><li>Ввод в эксплуатацию...,"{'id': 12, 'title': 'Нижний Новгород', 'declen...","{'id': 3, 'title': 'От 3 лет'}","{'id': 6, 'title': 'Полный рабочий день'}","{'id': 0, 'title': 'Не имеет значения'}",TNK

In [8]:
import ast

In [9]:
def get_title(col):
    col = ast.literal_eval(col)
    return col.get('title')

In [10]:
for col in ['town', 'experience', 'type_of_work', 'place_of_work']:
     df[col] = df[col].apply(get_title)

/tmp/ipykernel_15618/3826715785.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].apply(get_title)

In [11]:
df

,vacancy_category,profession,payment_from,payment_to,currency,candidat,vacancyRichText,town,experience,type_of_work,place_of_work,firm_name
0,AI,Стажер в IT отдел,0,0,rub,"Образование: программирование, интеллектуальны...","Образование: программирование, интеллектуальн...",Москва,Без опыта,Полный рабочий день,Не имеет значения,Аэрофлот
1,AI,Стажер разработчик интерфейсов,0,0,rub,Команда Банка Ozon создаёт и развивает сервисы...,<p>Команда Банка Ozon создаёт и развивает серв...,Москва,Без опыта,Полный рабочий день,Не имеет значения,OZON: Старт карьеры
2,AI,Контент-маркетолог,0,0,rub,"Привет,\nВ команде #mktngCROC открылась ваканс...","<p>Привет,</p>В команде #mktngCROC открылась в...",Москва,Без опыта,Полный рабочий день,Не имеет значения,КРОК
3,AI,Стажер в IT отдел,0,0,rub,Здесь занимаются поддержкой IT-платформ и их р...,Здесь занимаются поддержкой IT-платформ и их ...,Москва,Без опыта,Полный рабочий день,Не имеет значения,Добрый
4,AI,Стажер отдела операционной деятельности цифров...,0,0,rub,О компании и роли\n\nГруппа по управлению опер...,<p><b> О компании и роли</b><br><br>Группа по ...,Москва,Без опыта,Полный рабочий день,Не имеет значения,Disney
...,...,...,...,...,...,...,...,...,...,...,...,...
19817,"Начало карьеры, мало опыта",Специалист по расклейке листовок (подработка),20000,60000,rub,"Мы предлагаем:\n• Гибкий график, от 4 часов в ...",<p><b>Мы предлагаем:</b></p><ul><li>Гибкий гра...,Нижний Новгород,Без опыта,Частичная занятость / Совместительство,Не имеет значения,билайн
19818,"Начало карьеры, мало опыта","Системный администратор, IT-специалист (госслу...",65000,70000,rub,Обязанности:\n• Информационная безопасность (П...,<p><b><br /></b></p><b>Обязанности:</b><ul><li...,Нижний Новгород,От 1 года,Полный рабочий день,Не имеет значения,ФТС
19819,"Начало карьеры, мало опыта",Инженер-оператор КИМ и ВИМ,0,90000,rub,"Вакансия компании: ООО ""ПРОФ-НН""\nОписание ком...","<p>Вакансия компании: ООО ""ПРОФ-НН""</p><p>Опис...",Нижний Новгород,От 1 года,Полный рабочий день,Не имеет значения,"ООО ""ПРОФ-НН"""
19820,"Начало карьеры, мало опыта",DevOps специалист,0,0,rub,В ГК Русагро открыта вакансия DevOps\nЧто нужн...,<p>В ГК Русагро открыта вакансия DevOps</p><p>...,Нижний Новгород,От 3 лет,Полный рабочий день,Не имеет значения,Группа Компаний РУСАГРО
19821,"Начало карьеры, мало опыта",Инженер ПНР АСУТП,103000,118000,rub,Обязанности:\n• Ввод в эксплуатацию шкафного о...,<b>Обязанности:</b><ul><li>Ввод в эксплуатацию...,Нижний Новгород,От 3 лет,Полный рабочий день,Не имеет значения,TNK

In [12]:
df.currency.nunique()

1

In [13]:
df.drop(columns=['currency'], inplace=True)

/tmp/ipykernel_15618/1514593557.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['currency'], inplace=True)

In [14]:
df

,vacancy_category,profession,payment_from,payment_to,candidat,vacancyRichText,town,experience,type_of_work,place_of_work,firm_name
0,AI,Стажер в IT отдел,0,0,"Образование: программирование, интеллектуальны...","Образование: программирование, интеллектуальн...",Москва,Без опыта,Полный рабочий день,Не имеет значения,Аэрофлот
1,AI,Стажер разработчик интерфейсов,0,0,Команда Банка Ozon создаёт и развивает сервисы...,<p>Команда Банка Ozon создаёт и развивает серв...,Москва,Без опыта,Полный рабочий день,Не имеет значения,OZON: Старт карьеры
2,AI,Контент-маркетолог,0,0,"Привет,\nВ команде #mktngCROC открылась ваканс...","<p>Привет,</p>В команде #mktngCROC открылась в...",Москва,Без опыта,Полный рабочий день,Не имеет значения,КРОК
3,AI,Стажер в IT отдел,0,0,Здесь занимаются поддержкой IT-платформ и их р...,Здесь занимаются поддержкой IT-платформ и их ...,Москва,Без опыта,Полный рабочий день,Не имеет значения,Добрый
4,AI,Стажер отдела операционной деятельности цифров...,0,0,О компании и роли\n\nГруппа по управлению опер...,<p><b> О компании и роли</b><br><br>Группа по ...,Москва,Без опыта,Полный рабочий день,Не имеет значения,Disney
...,...,...,...,...,...,...,...,...,...,...,...
19817,"Начало карьеры, мало опыта",Специалист по расклейке листовок (подработка),20000,60000,"Мы предлагаем:\n• Гибкий график, от 4 часов в ...",<p><b>Мы предлагаем:</b></p><ul><li>Гибкий гра...,Нижний Новгород,Без опыта,Частичная занятость / Совместительство,Не имеет значения,билайн
19818,"Начало карьеры, мало опыта","Системный администратор, IT-специалист (госслу...",65000,70000,Обязанности:\n• Информационная безопасность (П...,<p><b><br /></b></p><b>Обязанности:</b><ul><li...,Нижний Новгород,От 1 года,Полный рабочий день,Не имеет значения,ФТС
19819,"Начало карьеры, мало опыта",Инженер-оператор КИМ и ВИМ,0,90000,"Вакансия компании: ООО ""ПРОФ-НН""\nОписание ком...","<p>Вакансия компании: ООО ""ПРОФ-НН""</p><p>Опис...",Нижний Новгород,От 1 года,Полный рабочий день,Не имеет значения,"ООО ""ПРОФ-НН"""
19820,"Начало карьеры, мало опыта",DevOps специалист,0,0,В ГК Русагро открыта вакансия DevOps\nЧто нужн...,<p>В ГК Русагро открыта вакансия DevOps</p><p>...,Нижний Новгород,От 3 лет,Полный рабочий день,Не имеет значения,Группа Компаний РУСАГРО
19821,"Начало карьеры, мало опыта",Инженер ПНР АСУТП,103000,118000,Обязанности:\n• Ввод в эксплуатацию шкафного о...,<b>Обязанности:</b><ul><li>Ввод в эксплуатацию...,Нижний Новгород,От 3 лет,Полный рабочий день,Не имеет значения,TNK

In [15]:
df.nunique()

vacancy_category     38
profession          230
payment_from         58
payment_to           53
candidat            246
vacancyRichText     246
town                  5
experience            4
type_of_work          5
place_of_work         2
firm_name           130
dtype: int64

In [16]:
df.place_of_work.value_counts()

place_of_work
Не имеет значения             19581
Удалённая работа (на дому)      241
Name: count, dtype: int64

In [17]:
df.type_of_work.value_counts()

type_of_work
Полный рабочий день                       19063
Частичная занятость / Совместительство      456
Работа вахтовым методом                     151
Сменный график работы                        76
Неполная дистанционная занятость             76
Name: count, dtype: int64

In [18]:
# Идея использования bs для очистки htmlвских артефактов

# Source - https://stackoverflow.com/a/12982689

# Posted by c24b, modified by community. See post 'Timeline' for change history

# Retrieved 2026-04-09, License - CC BY-SA 4.0

from bs4 import BeautifulSoup

In [19]:
def clean_text(col):
    soup = BeautifulSoup(col, 'lxml')
    return soup.get_text(separator=' ').strip()

In [20]:
df['vacancy_clean'] = df['vacancyRichText'].apply(clean_text)
df['candidat_clean'] = df['candidat'].apply(clean_text)

/tmp/ipykernel_15618/104472331.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['vacancy_clean'] = df['vacancyRichText'].apply(clean_text)
/tmp/ipykernel_15618/104472331.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['candidat_clean'] = df['candidat'].apply(clean_text)

In [21]:
df

,vacancy_category,profession,payment_from,payment_to,candidat,vacancyRichText,town,experience,type_of_work,place_of_work,firm_name,vacancy_clean,candidat_clean
0,AI,Стажер в IT отдел,0,0,"Образование: программирование, интеллектуальны...","Образование: программирование, интеллектуальн...",Москва,Без опыта,Полный рабочий день,Не имеет значения,Аэрофлот,"Образование: программирование, интеллектуальны...","Образование: программирование, интеллектуальны..."
1,AI,Стажер разработчик интерфейсов,0,0,Команда Банка Ozon создаёт и развивает сервисы...,<p>Команда Банка Ozon создаёт и развивает серв...,Москва,Без опыта,Полный рабочий день,Не имеет значения,OZON: Старт карьеры,Команда Банка Ozon создаёт и развивает сервисы...,Команда Банка Ozon создаёт и развивает сервисы...
2,AI,Контент-маркетолог,0,0,"Привет,\nВ команде #mktngCROC открылась ваканс...","<p>Привет,</p>В команде #mktngCROC открылась в...",Москва,Без опыта,Полный рабочий день,Не имеет значения,КРОК,"Привет, В команде #mktngCROC открылась ваканси...","Привет,\nВ команде #mktngCROC открылась ваканс..."
3,AI,Стажер в IT отдел,0,0,Здесь занимаются поддержкой IT-платформ и их р...,Здесь занимаются поддержкой IT-платформ и их ...,Москва,Без опыта,Полный рабочий день,Не имеет значения,Добрый,Здесь занимаются поддержкой IT-платформ и их р...,Здесь занимаются поддержкой IT-платформ и их р...
4,AI,Стажер отдела операционной деятельности цифров...,0,0,О компании и роли\n\nГруппа по управлению опер...,<p><b> О компании и роли</b><br><br>Группа по ...,Москва,Без опыта,Полный рабочий день,Не имеет значения,Disney,О компании и роли Группа по управлению операци...,О компании и роли\n\nГруппа по управлению опер...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19817,"Начало карьеры, мало опыта",Специалист по расклейке листовок (подработка),20000,60000,"Мы предлагаем:\n• Гибкий график, от 4 часов в ...",<p><b>Мы предлагаем:</b></p><ul><li>Гибкий гра...,Нижний Новгород,Без опыта,Частичная занятость / Совместительство,Не имеет значения,билайн,"Мы предлагаем: Гибкий график, от 4 часов в ден...","Мы предлагаем:\n• Гибкий график, от 4 часов в ..."
19818,"Начало карьеры, мало опыта","Системный администратор, IT-специалист (госслу...",65000,70000,Обязанности:\n• Информационная безопасность (П...,<p><b><br /></b></p><b>Обязанности:</b><ul><li...,Нижний Новгород,От 1 года,Полный рабочий день,Не имеет значения,ФТС,Обязанности: Информационная безопасность (ПДТК...,Обязанности:\n• Информационная безопасность (П...
19819,"Начало карьеры, мало опыта",Инженер-оператор КИМ и ВИМ,0,90000,"Вакансия компании: ООО ""ПРОФ-НН""\nОписание ком...","<p>Вакансия компании: ООО ""ПРОФ-НН""</p><p>Опис...",Нижний Новгород,От 1 года,Полный рабочий день,Не имеет значения,"ООО ""ПРОФ-НН""","Вакансия компании: ООО ""ПРОФ-НН"" Описание комп...","Вакансия компании: ООО ""ПРОФ-НН""\nОписание ком..."
19820,"Начало карьеры, мало опыта",DevOps специалист,0,0,В ГК Русагро открыта вакансия DevOps\nЧто нужн...,<p>В ГК Русагро открыта вакансия DevOps</p><p>...,Нижний Новгород,От 3 лет,Полный рабочий день,Не имеет значения,Группа Компаний РУСАГРО,В ГК Русагро открыта вакансия DevOps Что нужно...,В ГК Русагро открыта вакансия DevOps\nЧто нужн...
19821,"Начало карьеры, мало опыта",Инженер ПНР АСУТП,103000,118000,Обязанности:\n• Ввод в эксплуатацию шкафного о...,<b>Обязанности:</b><ul><li>Ввод в эксплуатацию...,Нижний Новгород,От 3 лет,Полный рабочий день,Не имеет значения,TNK,Обязанности: Ввод в эксплуатацию шкафного обор...,Обязанности:\n• Ввод в эксплуатацию шкафного о...

vacancy_clean по итогу почистился лучше, так что оставим его

In [22]:
df.drop(columns=['candidat_clean', 'vacancyRichText', 'candidat'], inplace=True)

/tmp/ipykernel_15618/2442349946.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['candidat_clean', 'vacancyRichText', 'candidat'], inplace=True)

In [23]:
df

,vacancy_category,profession,payment_from,payment_to,town,experience,type_of_work,place_of_work,firm_name,vacancy_clean
0,AI,Стажер в IT отдел,0,0,Москва,Без опыта,Полный рабочий день,Не имеет значения,Аэрофлот,"Образование: программирование, интеллектуальны..."
1,AI,Стажер разработчик интерфейсов,0,0,Москва,Без опыта,Полный рабочий день,Не имеет значения,OZON: Старт карьеры,Команда Банка Ozon создаёт и развивает сервисы...
2,AI,Контент-маркетолог,0,0,Москва,Без опыта,Полный рабочий день,Не имеет значения,КРОК,"Привет, В команде #mktngCROC открылась ваканси..."
3,AI,Стажер в IT отдел,0,0,Москва,Без опыта,Полный рабочий день,Не имеет значения,Добрый,Здесь занимаются поддержкой IT-платформ и их р...
4,AI,Стажер отдела операционной деятельности цифров...,0,0,Москва,Без опыта,Полный рабочий день,Не имеет значения,Disney,О компании и роли Группа по управлению операци...
...,...,...,...,...,...,...,...,...,...,...
19817,"Начало карьеры, мало опыта",Специалист по расклейке листовок (подработка),20000,60000,Нижний Новгород,Без опыта,Частичная занятость / Совместительство,Не имеет значения,билайн,"Мы предлагаем: Гибкий график, от 4 часов в ден..."
19818,"Начало карьеры, мало опыта","Системный администратор, IT-специалист (госслу...",65000,70000,Нижний Новгород,От 1 года,Полный рабочий день,Не имеет значения,ФТС,Обязанности: Информационная безопасность (ПДТК...
19819,"Начало карьеры, мало опыта",Инженер-оператор КИМ и ВИМ,0,90000,Нижний Новгород,От 1 года,Полный рабочий день,Не имеет значения,"ООО ""ПРОФ-НН""","Вакансия компании: ООО ""ПРОФ-НН"" Описание комп..."
19820,"Начало карьеры, мало опыта",DevOps специалист,0,0,Нижний Новгород,От 3 лет,Полный рабочий день,Не имеет значения,Группа Компаний РУСАГРО,В ГК Русагро открыта вакансия DevOps Что нужно...
19821,"Начало карьеры, мало опыта",Инженер ПНР АСУТП,103000,118000,Нижний Новгород,От 3 лет,Полный рабочий день,Не имеет значения,TNK,Обязанности: Ввод в эксплуатацию шкафного обор...

In [24]:
df.duplicated().sum()

np.int64(10360)

In [25]:
df.drop_duplicates(inplace=True)

/tmp/ipykernel_15618/3006716147.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)

In [26]:
df

,vacancy_category,profession,payment_from,payment_to,town,experience,type_of_work,place_of_work,firm_name,vacancy_clean
0,AI,Стажер в IT отдел,0,0,Москва,Без опыта,Полный рабочий день,Не имеет значения,Аэрофлот,"Образование: программирование, интеллектуальны..."
1,AI,Стажер разработчик интерфейсов,0,0,Москва,Без опыта,Полный рабочий день,Не имеет значения,OZON: Старт карьеры,Команда Банка Ozon создаёт и развивает сервисы...
2,AI,Контент-маркетолог,0,0,Москва,Без опыта,Полный рабочий день,Не имеет значения,КРОК,"Привет, В команде #mktngCROC открылась ваканси..."
3,AI,Стажер в IT отдел,0,0,Москва,Без опыта,Полный рабочий день,Не имеет значения,Добрый,Здесь занимаются поддержкой IT-платформ и их р...
4,AI,Стажер отдела операционной деятельности цифров...,0,0,Москва,Без опыта,Полный рабочий день,Не имеет значения,Disney,О компании и роли Группа по управлению операци...
...,...,...,...,...,...,...,...,...,...,...
19817,"Начало карьеры, мало опыта",Специалист по расклейке листовок (подработка),20000,60000,Нижний Новгород,Без опыта,Частичная занятость / Совместительство,Не имеет значения,билайн,"Мы предлагаем: Гибкий график, от 4 часов в ден..."
19818,"Начало карьеры, мало опыта","Системный администратор, IT-специалист (госслу...",65000,70000,Нижний Новгород,От 1 года,Полный рабочий день,Не имеет значения,ФТС,Обязанности: Информационная безопасность (ПДТК...
19819,"Начало карьеры, мало опыта",Инженер-оператор КИМ и ВИМ,0,90000,Нижний Новгород,От 1 года,Полный рабочий день,Не имеет значения,"ООО ""ПРОФ-НН""","Вакансия компании: ООО ""ПРОФ-НН"" Описание комп..."
19820,"Начало карьеры, мало опыта",DevOps специалист,0,0,Нижний Новгород,От 3 лет,Полный рабочий день,Не имеет значения,Группа Компаний РУСАГРО,В ГК Русагро открыта вакансия DevOps Что нужно...
19821,"Начало карьеры, мало опыта",Инженер ПНР АСУТП,103000,118000,Нижний Новгород,От 3 лет,Полный рабочий день,Не имеет значения,TNK,Обязанности: Ввод в эксплуатацию шкафного обор...

In [27]:
df.to_csv('superjob_df.csv', encoding='utf-8-sig')